package engine

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

func TestPromptText(t *testing.T) {
	long := strings.Repeat("word ", 4000)
	cases := []struct{ name, line, want string }{
		{"typed", `{"parentUuid":null,"isSidechain":false,"type":"user","message":{"role":"user","content":"fix the \"login\" bug\nplease"},"uuid":"u1","cwd":"/x"}`, "fix the \"login\" bug\nplease"},
		{"blocks", `{"type":"user","message":{"role":"user","content":[{"type":"image","source":{"type":"base64","data":"AAAA"}},{"type":"text","text":"what is this?"}]}}`, "what is this?"},
		{"other key order", `{"message":{"content":"hello","role":"user"},"type":"user"}`, "hello"},
		{"tool result", `{"type":"user","message":{"role":"user","content":[{"tool_use_id":"t1","type":"tool_result","content":[{"type":"text","text":"output"}]}]}}`, ""},
		{"meta", `{"type":"user","message":{"role":"user","content":"a note"},"isMeta":true}`, ""},
		{"compact summary", `{"type":"user","message":{"role":"user","content":"This session is being continued"},"isCompactSummary":true}`, ""},
		{"sidechain", `{"type":"user","isSidechain":true,"message":{"role":"user","content":"sub task"}}`, ""},
		{"assistant", `{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"hi"}]}}`, ""},
		{"not json", `garbage {{{`, ""},
		{"empty", ``, ""},
		// The script cuts long lines: the text is still found, as far as it goes.
		{"cut in the text", `{"parentUuid":null,"type":"user","message":{"role":"user","content":"deploy the api to stag`, "deploy the api to stag"},
		{"cut in an escape", `{"type":"user","message":{"role":"user","content":"first line\`, "first line"},
		{"cut in a unicode escape", `{"type":"user","message":{"role":"user","content":"café and \u00`, "café and "},
		{"cut blocks", `{"type":"user","message":{"role":"user","content":[{"type":"text","text":"look at the lo`, "look at the lo"},
		{"cut tool result", `{"type":"user","message":{"role":"user","content":[{"tool_use_id":"t","type":"tool_result","content":[{"type":"text","text":"lots of out`, ""},
		{"cut before the text", `{"type":"user","message":{"role":"us`, ""},
		{"cut, not a user line", `{"type":"assistant","message":{"role":"user","content":"x`, ""},
	}
	for _, c := range cases {
		if got := promptText(c.line); got != c.want {
			t.Errorf("%s: got %q, want %q", c.name, got, c.want)
		}
	}
	// A huge line: whole, and cut to what the script sends.
	line := who{cwd: "/x", day: "2026-01-01"}.user("00:00:00", long)
	if got := promptText(line); got != long {
		t.Errorf("huge line: %d bytes, want %d", len(got), len(long))
	}
	if got := promptText(line[:2500]); !strings.HasPrefix(got, "word word word") || len(got) < 2000 {
		t.Errorf("huge line, cut: %d bytes %q…", len(got), got[:min(len(got), 20)])
	}
}

func TestCleanPrompt(t *testing.T) {
	cases := []struct{ in, want string }{
		{"  fix the   login\n\nbug  ", "fix the login bug"},
		{"<system-reminder>\nremember things\n</system-reminder>\n\nactual question", "actual question"},
		{"<ide_opened_file>The user opened x.go</ide_opened_file><system-reminder>y</system-reminder> rename it", "rename it"},
		{"<system-reminder>cut before the end", ""},
		{"<command-name>/review</command-name>\n<command-message>review</command-message>\n<command-args>PR 42</command-args>", "/review PR 42"},
		{"<command-message>init</command-message><command-name>/init</command-name>", ""},
		{"<command-name>/clear</command-name><command-args></command-args>", ""},
		{"<local-command-stdout>Set model to opus</local-command-stdout>", ""},
		{"<task-notification>\n<task-id>abc</task-id>", ""},
		{`<cross-session-message from="x">hello</cross-session-message>`, ""},
		{"<bash-input>ls</bash-input>", ""},
		{"Caveat: The messages below were generated by the user while running local commands.", ""},
		{"[Request interrupted by user]", ""},
		{"<div> is not centred, why?", "<div> is not centred, why?"},
		{"", ""},
	}
	for _, c := range cases {
		if got := cleanPrompt(c.in); got != c.want {
			t.Errorf("cleanPrompt(%q) = %q, want %q", c.in, got, c.want)
		}
	}
	got := cleanPrompt(strings.Repeat("é ", 500))
	if r := []rune(got); len(r) != titleLen || r[len(r)-1] != '…' {
		t.Errorf("long prompt: %d characters, ends %q", len(r), string(r[len(r)-3:]))
	}
}

func TestJSONText(t *testing.T) {
	cases := []struct{ in, want string }{
		{`plain`, "plain"},
		{`a\nb\tc\\d\"e\/f`, "a\nb\tc\\d\"e/f"},
		{`café 😀!`, "café 😀!"},
		{`lone \ud83d half`, "lone � half"},
		{`cut \u00`, "cut "},
		{`cut \`, "cut "},
		{"caf\xc3", "caf"},       // a character split by the cut
		{"\xa9 start", " start"}, // and at the start
	}
	for _, c := range cases {
		if got := jsonText(c.in); got != c.want {
			t.Errorf("jsonText(%q) = %q, want %q", c.in, got, c.want)
		}
	}
	if v, ok := jsonField(`{"type":"ai-title","aiTitle":"Fix \"flaky\" tests","sessionId":"x"}`, "aiTitle"); !ok || v != `Fix "flaky" tests` {
		t.Errorf("jsonField: %q %v", v, ok)
	}
	if v, ok := jsonField(`{"type":"last-prompt","lastPrompt":"cut he`, "lastPrompt"); !ok || v != "cut he" {
		t.Errorf("jsonField, cut: %q %v", v, ok)
	}
	// A key named inside a string isn't a key: the quotes there are escaped.
	if v, ok := jsonField(`{"content":"say \"aiTitle\":\"x\" now","aiTitle":"real"}`, "aiTitle"); !ok || v != "real" {
		t.Errorf("jsonField, key in a string: %q %v", v, ok)
	}
	if _, ok := jsonField(`{"type":"mode"}`, "aiTitle"); ok {
		t.Error("jsonField found a key that isn't there")
	}
}

func TestProjectDir(t *testing.T) {
	cases := []struct{ folder, cwd, want string }{
		{"-Users-me-code-api", "/Users/me/code/api", "/Users/me/code/api"},
		{"-Users-me-code-api", "/Users/me/code/api/cmd/server", "/Users/me/code/api"}, // carried on after a cd
		{"-home-me--config-app", "/home/me/.config/app", "/home/me/.config/app"},
		{"-somewhere-else", "/Users/me/code/api", "/Users/me/code/api"}, // no parent matches: as the file says
		{"-Users-me", "", ""},
	}
	for _, c := range cases {
		if got := projectDir(c.folder, c.cwd); got != c.want {
			t.Errorf("projectDir(%q, %q) = %q, want %q", c.folder, c.cwd, got, c.want)
		}
	}
}

func TestParseHistory(t *testing.T) {
	huge := `{"parentUuid":null,"type":"user","message":{"role":"user","content":"` + strings.Repeat("investigate the slow query ", 200)
	out := strings.Join([]string{
		"Warning: something ssh said",
		"@@conv\t-home-me-api\taaaaaaaa-0000-0000-0000-000000000001\t1700000000\t5000\tcli",
		`c	/home/me/api`,
		`b	main`,
		`s	2026-03-01T10:00:00.000Z`,
		`r	1`,
		`t	{"type":"custom-title","customTitle":"Billing  refactor","sessionId":"x"}`,
		`t	{"type":"ai-title","aiTitle":"Refactor billing module","sessionId":"x"}`,
		"@@conv\t-home-me-api\taaaaaaaa-0000-0000-0000-000000000002\t1700000100\t900\tcli",
		`c	/home/me/api/sub\/dir`,
		`b	HEAD`,
		`s	2026-03-02T10:00:00.000Z`,
		`t	{"type":"ai-title","aiTitle":"Add \"retry\" to uploads","sessionId":"x"}`,
		`t	{"type":"last-prompt","lastPrompt":"and now the tests","leafUuid":"l"}`,
		// No title: the first thing really said, past a command and a note.
		"@@conv\t-home-me-web\taaaaaaaa-0000-0000-0000-000000000003\t1700000200\t900\tcli",
		`c	/home/me/web`,
		`u	{"type":"user","message":{"role":"user","content":"<command-name>/clear</command-name>"}}`,
		`u	not json at all`,
		`u	{"type":"user","message":{"role":"user","content":"<system-reminder>x</system-reminder>why is the page blank?"}}`,
		`u	{"type":"user","message":{"role":"user","content":"second question"}}`,
		// A huge first line, cut by the script.
		"@@conv\t-home-me-db\taaaaaaaa-0000-0000-0000-000000000004\t1700000300\t9000000\tcli",
		`c	/home/me/db`,
		"u\t" + huge[:2500],
		// A run started by a script: its queued prompt names it.
		"@@conv\t-home-me-jobs\taaaaaaaa-0000-0000-0000-000000000005\t1700000400\t900\tsdk-py",
		`c	/home/me/jobs`,
		`q	{"type":"queue-operation","operation":"enqueue","timestamp":"2026-03-05T10:00:00Z","sessionId":"x","content":"Summarise the nightly report"}`,
		// Only its last prompt is known, and no time stamp: the file's time counts.
		"@@conv\t-home-me-old\taaaaaaaa-0000-0000-0000-000000000006\t1600000000\t900\t",
		`c	/home/me/old`,
		`t	{"type":"last-prompt","lastPrompt":"ship it","leafUuid":"l"}`,
		// Nothing was said: left out. And a record twice: kept once.
		"@@conv\t-home-me-empty\taaaaaaaa-0000-0000-0000-000000000007\t1700000500\t200\tcli",
		`c	/home/me/empty`,
		`u	{"type":"user","message":{"role":"user","content":"<local-command-stdout>ok</local-command-stdout>"}}`,
		"@@conv\t-home-me-api\taaaaaaaa-0000-0000-0000-000000000001\t1700000000\t5000\tcli",
		`c	/home/me/api`,
		`t	{"type":"ai-title","aiTitle":"A copy","sessionId":"x"}`,
		"@@conv\tbad id\tnot an id!\t1\t1\tcli",
		`t	{"type":"ai-title","aiTitle":"Never shown","sessionId":"x"}`,
		"@@end\t7\t7",
		"@@n\taaaaaaaa-0000-0000-0000-000000000001\t42",
		"@@n\taaaaaaaa-0000-0000-0000-000000000003\tx",
		"",
	}, "\n")
	list := parseHistory("box", out)
	var got []string
	for _, c := range list {
		got = append(got, c.ID[len(c.ID)-1:]+" "+c.Title)
	}
	want := []string{
		"2 Add \"retry\" to uploads",
		"1 Billing refactor",
		"5 Summarise the nightly report",
		"4 " + oneLine(strings.Repeat("investigate the slow query ", 200), titleLen),
		"3 why is the page blank?",
		"6 ship it",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("conversations:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
	by := map[string]Conversation{}
	for _, c := range list {
		by[c.ID[len(c.ID)-1:]] = c
	}
	if c := by["1"]; c.Machine != "box" || c.Dir != "/home/me/api" || c.Branch != "main" || !c.Running || c.Messages != 42 || c.Auto || c.Size != 5000 || !c.Updated.Equal(time.Date(2026, 3, 1, 10, 0, 0, 0, time.UTC)) {
		t.Errorf("first: %+v", c)
	}
	if c := by["2"]; c.Dir != "/home/me/api" || c.Branch != "" || c.Running || c.Messages != 0 {
		t.Errorf("second (folder below the project, detached HEAD): %+v", c)
	}
	if c := by["5"]; !c.Auto {
		t.Errorf("a script's run: %+v", c)
	}
	if c := by["6"]; !c.Updated.Equal(time.Unix(1600000000, 0)) {
		t.Errorf("no time stamp: %+v", c)
	}
	if r := []rune(by["4"].Title); len(r) != titleLen {
		t.Errorf("huge line: title of %d characters", len(r))
	}
}

func TestMarkLive(t *testing.T) {
	list := []Conversation{{Machine: "box", ID: "one"}, {Machine: "box", ID: "two"}, {Machine: "mini", ID: "one"}, {Machine: "box", ID: "three"}}
	markLive(list, []Session{
		{Machine: "box", Name: "claude-api", Claude: true, State: "idle", SID: "one"},
		{Machine: "box", Name: "claude-left", Claude: true, State: "", SID: "two"}, // Claude has left that session
		{Machine: "box", Name: "shell-ab12", SID: ""},
	})
	if list[0].Live != "claude-api" || list[1].Live != "" || list[2].Live != "" || list[3].Live != "" {
		t.Errorf("live: %+v", list)
	}
}

// transcript writes a conversation file: one line of JSON per entry, as given.
func transcript(t *testing.T, root, folder, id string, lines ...string) string {
	t.Helper()
	dir := filepath.Join(root, "projects", folder)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, id+".jsonl")
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

// who writes transcript lines the way Claude Code does, key for key and in its order (the
// scripts read them as text), for a conversation in a folder.
type who struct{ cwd, branch, day, entry string }

func js(s string) string { return `"` + jsonFragment(s) + `"` }

func (w who) tail(at string) string {
	entry, branch := w.entry, w.branch
	if entry == "" {
		entry = "cli"
	}
	if branch == "" {
		branch = "main"
	}
	return `"timestamp":"` + w.day + `T` + at + `.000Z","userType":"external","entrypoint":"` + entry + `","cwd":` + js(w.cwd) + `,"sessionId":"s","version":"2.1.0","gitBranch":` + js(branch) + `}`
}

// user is something typed; flags are extra fields such as `"isMeta":true`.
func (w who) user(at, text string, flags ...string) string {
	extra := ""
	for _, f := range flags {
		extra += f + ","
	}
	return `{"parentUuid":null,"isSidechain":false,"promptId":"p","type":"user","message":{"role":"user","content":` + js(text) + `},` + extra + `"uuid":"u-` + at + `",` + w.tail(at)
}

// userBlocks is something typed that Claude Code stored as blocks (a picture, then text).
func (w who) userBlocks(at, text string) string {
	return `{"parentUuid":null,"isSidechain":false,"promptId":"p","type":"user","message":{"role":"user","content":[{"type":"image","source":{"type":"base64","media_type":"image/png","data":"iVBORw0KGgo"}},{"type":"text","text":` + js(text) + `}]},"uuid":"u-` + at + `",` + w.tail(at)
}

func (w who) assistant(at, text string) string {
	return `{"parentUuid":"p","isSidechain":false,"message":{"model":"m","id":"msg_1","type":"message","role":"assistant","content":[{"type":"text","text":` + js(text) + `}],"stop_reason":null},"requestId":"r","type":"assistant","uuid":"a-` + at + `",` + w.tail(at)
}

func (w who) thinking(at, text string) string {
	return `{"parentUuid":"p","isSidechain":false,"message":{"model":"m","id":"msg_1","type":"message","role":"assistant","content":[{"type":"thinking","thinking":` + js(text) + `,"signature":"c2ln"}],"stop_reason":null},"requestId":"r","type":"assistant","uuid":"k-` + at + `",` + w.tail(at)
}

func (w who) toolUse(at, command string) string {
	return `{"parentUuid":"p","isSidechain":false,"message":{"model":"m","id":"msg_1","type":"message","role":"assistant","content":[{"type":"tool_use","id":"toolu_1","name":"Bash","input":{"command":` + js(command) + `}}],"stop_reason":null},"requestId":"r","type":"assistant","uuid":"t-` + at + `",` + w.tail(at)
}

func (w who) toolResult(at, text string) string {
	return `{"parentUuid":"p","isSidechain":false,"type":"user","message":{"role":"user","content":[{"tool_use_id":"toolu_1","type":"tool_result","content":[{"type":"text","text":` + js(text) + `}]}]},"uuid":"r-` + at + `","toolUseResult":{"stdout":` + js(text) + `},` + w.tail(at)
}

func aiTitle(s string) string { return `{"type":"ai-title","aiTitle":` + js(s) + `,"sessionId":"s"}` }
func customTitle(s string) string {
	return `{"type":"custom-title","customTitle":` + js(s) + `,"sessionId":"s"}`
}

// scriptHome points the scripts at a folder of the test's own, and keeps sky's files out of
// the real ones. Skipped where the scripts can't run.
func scriptHome(t *testing.T) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("needs a POSIX shell")
	}
	if _, err := exec.LookPath("perl"); err != nil {
		t.Skip("perl is not installed")
	}
	root := t.TempDir()
	t.Setenv("CLAUDE_CONFIG_DIR", root)
	t.Setenv("SKYBUILD_HOME", t.TempDir())
	t.Setenv("SKY_TMUX_SOCKET", fmt.Sprintf("skytest-h%d", os.Getpid()))
	return root
}

func age(t *testing.T, path string, d time.Duration) {
	t.Helper()
	at := time.Now().Add(-d)
	if err := os.Chtimes(path, at, at); err != nil {
		t.Fatal(err)
	}
}

// The real script against transcripts made here.
func TestHistoryScript(t *testing.T) {
	root := scriptHome(t)
	filler := strings.Repeat("x", 3000)
	api := who{cwd: "/work/api", day: "2026-03-05"}
	big := []string{`{"type":"mode","mode":"normal","sessionId":"s"}`, api.user("09:00:00", "start of a long one")} // far more than the script reads at either end
	for i := 0; i < 120; i++ {
		at := fmt.Sprintf("10:%02d:%02d", i/60, i%60)
		big = append(big, api.toolResult(at, filler), api.assistant(at, fmt.Sprint("step ", i, " ", filler)))
	}
	big = append(big, aiTitle("Long migration"), `{"type":"last-prompt","lastPrompt":"keep going","leafUuid":"l"}`)
	age(t, transcript(t, root, "-work-api", "11111111-aaaa-bbbb-cccc-000000000001", big...), 1*time.Hour)

	// Carried on below the project folder, on another branch; no title, and a command first.
	cmd := who{cwd: "/work/api/cmd", branch: "fix/build", day: "2026-03-04"}
	age(t, transcript(t, root, "-work-api", "11111111-aaaa-bbbb-cccc-000000000002",
		cmd.user("09:00:00", "<command-name>/model</command-name>\n<command-message>model</command-message>"),
		cmd.user("09:10:00", "why does  the build\nfail?"),
		cmd.assistant("09:10:05", "Because of a missing import."),
		cmd.toolResult("09:10:06", "ok"),
		cmd.user("09:30:00", "thanks"),
	), 2*time.Hour)
	// One huge first message and no title: the title is the start of it.
	notes := who{cwd: "/work/notes", day: "2026-03-03"}
	age(t, transcript(t, root, "-work-notes", "11111111-aaaa-bbbb-cccc-000000000003",
		notes.user("09:00:00", strings.Repeat("summarise this log ", 20000)),
	), 3*time.Hour)
	// The user's own name for it wins over Claude's.
	web := who{cwd: "/work/web", day: "2026-03-02"}
	age(t, transcript(t, root, "-work-web", "11111111-aaaa-bbbb-cccc-000000000004",
		customTitle("Landing page"),
		web.userBlocks("09:00:00", "make the hero bigger"),
		aiTitle("Hero section sizing"),
		"this line is not JSON",
		"",
	), 4*time.Hour)
	// Started by a script.
	jobs := who{cwd: "/work/jobs", day: "2026-03-01", entry: "sdk-py"}
	age(t, transcript(t, root, "-work-jobs", "11111111-aaaa-bbbb-cccc-000000000005",
		`{"type":"queue-operation","operation":"enqueue","timestamp":"2026-03-01T09:00:00.000Z","sessionId":"s","content":"Classify the tickets"}`,
		jobs.user("09:00:00", "Classify the tickets"),
		jobs.assistant("09:00:05", "Done."),
	), 5*time.Hour)
	// Nothing was said in these: a bare command, and a file with no folder at all.
	transcript(t, root, "-work-web", "11111111-aaaa-bbbb-cccc-000000000006", web.user("11:00:00", "<command-name>/usage</command-name>"), web.user("11:00:01", "<local-command-stdout>42%</local-command-stdout>"))
	transcript(t, root, "-work-web", "11111111-aaaa-bbbb-cccc-000000000007", `{"type":"mode","mode":"normal","sessionId":"s"}`)
	// Not transcripts.
	transcript(t, root, "-work-web", "notes", "x")
	if err := os.MkdirAll(filepath.Join(root, "projects", "-work-web", "11111111-aaaa-bbbb-cccc-000000000004", "subagents"), 0o755); err != nil {
		t.Fatal(err)
	}

	e := New()
	ctx := context.Background()
	list, err := e.History(ctx, LocalMachine, HistoryOptions{Sessions: []Session{{Machine: LocalMachine, Name: "claude-web", Claude: true, State: "idle", SID: "11111111-aaaa-bbbb-cccc-000000000004"}}})
	if err != nil {
		t.Fatal(err)
	}
	var got []string
	for _, c := range list {
		got = append(got, fmt.Sprintf("%s|%s|%s|%s|%d|auto=%v|live=%s", c.ID[len(c.ID)-1:], c.Title, c.Dir, c.Branch, c.Messages, c.Auto, c.Live))
	}
	want := []string{
		"1|Long migration|/work/api|main|121|auto=false|live=",
		"2|why does the build fail?|/work/api|fix/build|3|auto=false|live=",
		"3|" + oneLine(strings.Repeat("summarise this log ", 20), titleLen) + "|/work/notes|main|1|auto=false|live=",
		"4|Landing page|/work/web|main|1|auto=false|live=claude-web",
		"5|Classify the tickets|/work/jobs|main|0|auto=true|live=",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("history:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
	for i, c := range list {
		if c.Machine != LocalMachine || c.Size == 0 || c.Updated.IsZero() || (i > 0 && c.Updated.After(list[i-1].Updated)) {
			t.Errorf("conversation %d: %+v", i, c)
		}
	}
	if !list[1].Updated.Equal(time.Date(2026, 3, 4, 9, 30, 0, 0, time.UTC)) {
		t.Errorf("the last thing said dates it: %v", list[1].Updated)
	}

	// Limits: the newest typed ones, and none started by scripts.
	list, err = e.History(ctx, LocalMachine, HistoryOptions{Limit: 2, Auto: -1, Sessions: []Session{}})
	if err != nil || len(list) != 2 || list[0].Title != "Long migration" || list[1].Auto {
		t.Fatalf("limited: %v %+v", err, list)
	}
	// By the start of an ID.
	list, err = e.History(ctx, LocalMachine, HistoryOptions{ID: "11111111-aaaa-bbbb-cccc-000000000003", Sessions: []Session{}})
	if err != nil || len(list) != 1 || list[0].Dir != "/work/notes" {
		t.Fatalf("by ID: %v %+v", err, list)
	}
	if list, err = e.History(ctx, LocalMachine, HistoryOptions{ID: "1111", Sessions: []Session{}}); err != nil || len(list) != 5 {
		t.Fatalf("by the start of an ID: %v %d", err, len(list))
	}
	if _, err = e.History(ctx, LocalMachine, HistoryOptions{ID: "x; rm -rf /", Sessions: []Session{}}); err == nil {
		t.Fatal("an ID that isn't one must be refused")
	}
	// No transcripts at all is not an error.
	t.Setenv("CLAUDE_CONFIG_DIR", t.TempDir())
	if list, err = e.History(ctx, LocalMachine, HistoryOptions{Sessions: []Session{}}); err != nil || len(list) != 0 {
		t.Fatalf("empty: %v %v", err, list)
	}
}
