// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIKeys() {
  return window['go']['main']['App']['APIKeys']();
}

export function APIProviders() {
  return window['go']['main']['App']['APIProviders']();
}

export function AddClaudeAccount(arg1, arg2) {
  return window['go']['main']['App']['AddClaudeAccount'](arg1, arg2);
}

export function AddLink(arg1) {
  return window['go']['main']['App']['AddLink'](arg1);
}

export function AddMachine(arg1) {
  return window['go']['main']['App']['AddMachine'](arg1);
}

export function AgentVersions(arg1) {
  return window['go']['main']['App']['AgentVersions'](arg1);
}

export function AgentsOn(arg1) {
  return window['go']['main']['App']['AgentsOn'](arg1);
}

export function AppIcon() {
  return window['go']['main']['App']['AppIcon']();
}

export function CancelOp(arg1) {
  return window['go']['main']['App']['CancelOp'](arg1);
}

export function Catalog(arg1) {
  return window['go']['main']['App']['Catalog'](arg1);
}

export function CheckClaudeAccounts() {
  return window['go']['main']['App']['CheckClaudeAccounts']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClaudeAccounts() {
  return window['go']['main']['App']['ClaudeAccounts']();
}

export function ClaudeAutoSwitch() {
  return window['go']['main']['App']['ClaudeAutoSwitch']();
}

export function ClaudeMoveSessions() {
  return window['go']['main']['App']['ClaudeMoveSessions']();
}

export function ClaudePreciseScroll() {
  return window['go']['main']['App']['ClaudePreciseScroll']();
}

export function ClaudeStatus() {
  return window['go']['main']['App']['ClaudeStatus']();
}

export function ClaudeStrategy() {
  return window['go']['main']['App']['ClaudeStrategy']();
}

export function ClipboardText() {
  return window['go']['main']['App']['ClipboardText']();
}

export function Clone(arg1, arg2, arg3) {
  return window['go']['main']['App']['Clone'](arg1, arg2, arg3);
}

export function CloseShell(arg1, arg2) {
  return window['go']['main']['App']['CloseShell'](arg1, arg2);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CloseTunnel(arg1) {
  return window['go']['main']['App']['CloseTunnel'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CreateMachine(arg1) {
  return window['go']['main']['App']['CreateMachine'](arg1);
}

export function Credentials() {
  return window['go']['main']['App']['Credentials']();
}

export function DeleteMachine(arg1, arg2) {
  return window['go']['main']['App']['DeleteMachine'](arg1, arg2);
}

export function DiscoverMachines() {
  return window['go']['main']['App']['DiscoverMachines']();
}

export function FillSpec(arg1) {
  return window['go']['main']['App']['FillSpec'](arg1);
}

export function FindFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FindFile'](arg1, arg2, arg3, arg4);
}

export function FocusSession(arg1, arg2) {
  return window['go']['main']['App']['FocusSession'](arg1, arg2);
}

export function GrowDisk(arg1, arg2) {
  return window['go']['main']['App']['GrowDisk'](arg1, arg2);
}

export function History(arg1) {
  return window['go']['main']['App']['History'](arg1);
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function InstallTmux() {
  return window['go']['main']['App']['InstallTmux']();
}

export function JoinTailscale(arg1) {
  return window['go']['main']['App']['JoinTailscale'](arg1);
}

export function KillSession(arg1, arg2) {
  return window['go']['main']['App']['KillSession'](arg1, arg2);
}

export function LastSyncAll() {
  return window['go']['main']['App']['LastSyncAll']();
}

export function Links() {
  return window['go']['main']['App']['Links']();
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function LocalTmux() {
  return window['go']['main']['App']['LocalTmux']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function MachineHealth() {
  return window['go']['main']['App']['MachineHealth']();
}

export function Machines() {
  return window['go']['main']['App']['Machines']();
}

export function MintClaudeToken() {
  return window['go']['main']['App']['MintClaudeToken']();
}

export function MoveClaudeAccount(arg1, arg2) {
  return window['go']['main']['App']['MoveClaudeAccount'](arg1, arg2);
}

export function MoveFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2, arg3);
}

export function NewSession(arg1, arg2) {
  return window['go']['main']['App']['NewSession'](arg1, arg2);
}

export function NewWindow() {
  return window['go']['main']['App']['NewWindow']();
}

export function NewWindowWith(arg1) {
  return window['go']['main']['App']['NewWindowWith'](arg1);
}

export function NextWindow() {
  return window['go']['main']['App']['NextWindow']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenAtLogin() {
  return window['go']['main']['App']['OpenAtLogin']();
}

export function OpenLocalTerminal(arg1, arg2) {
  return window['go']['main']['App']['OpenLocalTerminal'](arg1, arg2);
}

export function OpenLocalTerminalIn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenLocalTerminalIn'](arg1, arg2, arg3, arg4);
}

export function OpenPeeked(arg1) {
  return window['go']['main']['App']['OpenPeeked'](arg1);
}

export function OpenPort(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenPort'](arg1, arg2, arg3);
}

export function OpenScreen(arg1) {
  return window['go']['main']['App']['OpenScreen'](arg1);
}

export function OpenSessionTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenSessionTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenTerminal'](arg1, arg2, arg3, arg4);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Ops() {
  return window['go']['main']['App']['Ops']();
}

export function OtherSync(arg1) {
  return window['go']['main']['App']['OtherSync'](arg1);
}

export function PaneGit(arg1, arg2) {
  return window['go']['main']['App']['PaneGit'](arg1, arg2);
}

export function PaneIntent(arg1) {
  return window['go']['main']['App']['PaneIntent'](arg1);
}

export function PeekFile(arg1, arg2) {
  return window['go']['main']['App']['PeekFile'](arg1, arg2);
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function PlanMove(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlanMove'](arg1, arg2, arg3);
}

export function Ports(arg1) {
  return window['go']['main']['App']['Ports'](arg1);
}

export function ProjectAdd(arg1) {
  return window['go']['main']['App']['ProjectAdd'](arg1);
}

export function ProjectBring(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProjectBring'](arg1, arg2, arg3);
}

export function ProjectForget(arg1, arg2) {
  return window['go']['main']['App']['ProjectForget'](arg1, arg2);
}

export function ProjectSend(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProjectSend'](arg1, arg2, arg3);
}

export function ProjectSetRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProjectSetRemote'](arg1, arg2, arg3);
}

export function Projects(arg1) {
  return window['go']['main']['App']['Projects'](arg1);
}

export function ProviderStatuses(arg1) {
  return window['go']['main']['App']['ProviderStatuses'](arg1);
}

export function Pull(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Pull'](arg1, arg2, arg3, arg4);
}

export function Push(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Push'](arg1, arg2, arg3, arg4);
}

export function RecentFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecentFiles'](arg1, arg2, arg3);
}

export function RecentFolders(arg1) {
  return window['go']['main']['App']['RecentFolders'](arg1);
}

export function RefreshHealth() {
  return window['go']['main']['App']['RefreshHealth']();
}

export function RefreshMachines() {
  return window['go']['main']['App']['RefreshMachines']();
}

export function RemoveAPIKey(arg1) {
  return window['go']['main']['App']['RemoveAPIKey'](arg1);
}

export function RemoveClaudeAccount(arg1) {
  return window['go']['main']['App']['RemoveClaudeAccount'](arg1);
}

export function RemoveLink(arg1) {
  return window['go']['main']['App']['RemoveLink'](arg1);
}

export function RenameClaudeAccount(arg1, arg2) {
  return window['go']['main']['App']['RenameClaudeAccount'](arg1, arg2);
}

export function ResizeMachine(arg1, arg2) {
  return window['go']['main']['App']['ResizeMachine'](arg1, arg2);
}

export function RestartClaude(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestartClaude'](arg1, arg2, arg3, arg4);
}

export function RestartMachine(arg1) {
  return window['go']['main']['App']['RestartMachine'](arg1);
}

export function RestartToUpdate() {
  return window['go']['main']['App']['RestartToUpdate']();
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function RevealPeeked(arg1) {
  return window['go']['main']['App']['RevealPeeked'](arg1);
}

export function RunLink(arg1) {
  return window['go']['main']['App']['RunLink'](arg1);
}

export function SavePeeked(arg1) {
  return window['go']['main']['App']['SavePeeked'](arg1);
}

export function SaveScreenLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveScreenLogin'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWindowFrame() {
  return window['go']['main']['App']['SaveWindowFrame']();
}

export function SaveWindowLayout(arg1) {
  return window['go']['main']['App']['SaveWindowLayout'](arg1);
}

export function SearchShow(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchShow'](arg1, arg2, arg3);
}

export function SearchStart(arg1, arg2) {
  return window['go']['main']['App']['SearchStart'](arg1, arg2);
}

export function SearchStop() {
  return window['go']['main']['App']['SearchStop']();
}

export function SessionPorts(arg1) {
  return window['go']['main']['App']['SessionPorts'](arg1);
}

export function Sessions() {
  return window['go']['main']['App']['Sessions']();
}

export function SetAPIKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2, arg3, arg4);
}

export function SetAPIKeyMachines(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKeyMachines'](arg1, arg2);
}

export function SetAPIKeySync(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKeySync'](arg1, arg2);
}

export function SetAppIcon(arg1) {
  return window['go']['main']['App']['SetAppIcon'](arg1);
}

export function SetAutoUpdate(arg1) {
  return window['go']['main']['App']['SetAutoUpdate'](arg1);
}

export function SetClaudeAccountEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetClaudeAccountEnabled'](arg1, arg2);
}

export function SetClaudeAutoSwitch(arg1) {
  return window['go']['main']['App']['SetClaudeAutoSwitch'](arg1);
}

export function SetClaudeMoveSessions(arg1) {
  return window['go']['main']['App']['SetClaudeMoveSessions'](arg1);
}

export function SetClaudePreciseScroll(arg1) {
  return window['go']['main']['App']['SetClaudePreciseScroll'](arg1);
}

export function SetClaudeStrategy(arg1) {
  return window['go']['main']['App']['SetClaudeStrategy'](arg1);
}

export function SetClaudeToken(arg1) {
  return window['go']['main']['App']['SetClaudeToken'](arg1);
}

export function SetIdle(arg1, arg2) {
  return window['go']['main']['App']['SetIdle'](arg1, arg2);
}

export function SetLinkWatch(arg1, arg2) {
  return window['go']['main']['App']['SetLinkWatch'](arg1, arg2);
}

export function SetOpenAtLogin(arg1) {
  return window['go']['main']['App']['SetOpenAtLogin'](arg1);
}

export function SetSyncItems(arg1, arg2) {
  return window['go']['main']['App']['SetSyncItems'](arg1, arg2);
}

export function SetTailscaleAuthKey(arg1) {
  return window['go']['main']['App']['SetTailscaleAuthKey'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function StartMachine(arg1) {
  return window['go']['main']['App']['StartMachine'](arg1);
}

export function StopMachine(arg1) {
  return window['go']['main']['App']['StopMachine'](arg1);
}

export function SyncMachines(arg1, arg2) {
  return window['go']['main']['App']['SyncMachines'](arg1, arg2);
}

export function TailscaleStatus() {
  return window['go']['main']['App']['TailscaleStatus']();
}

export function TakeOverSync(arg1) {
  return window['go']['main']['App']['TakeOverSync'](arg1);
}

export function TakeSession(arg1, arg2) {
  return window['go']['main']['App']['TakeSession'](arg1, arg2);
}

export function Terminal(arg1) {
  return window['go']['main']['App']['Terminal'](arg1);
}

export function TerminalInfo(arg1) {
  return window['go']['main']['App']['TerminalInfo'](arg1);
}

export function TestAPIKey(arg1) {
  return window['go']['main']['App']['TestAPIKey'](arg1);
}

export function Tunnels() {
  return window['go']['main']['App']['Tunnels']();
}

export function UpdateInfo() {
  return window['go']['main']['App']['UpdateInfo']();
}

export function UseClaudeAccount(arg1) {
  return window['go']['main']['App']['UseClaudeAccount'](arg1);
}

export function WatchedLinks() {
  return window['go']['main']['App']['WatchedLinks']();
}

export function WindowInfo() {
  return window['go']['main']['App']['WindowInfo']();
}

export function WindowLayout() {
  return window['go']['main']['App']['WindowLayout']();
}

export function WindowSessions(arg1) {
  return window['go']['main']['App']['WindowSessions'](arg1);
}

export function WindowsCleared(arg1) {
  return window['go']['main']['App']['WindowsCleared'](arg1);
}
