// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {main} from '../models';
import {model} from '../models';
import {syncer} from '../models';
import {term} from '../models';
import {folders} from '../models';

export function APIKeys():Promise<Array<engine.APIKeyView>>;

export function APIProviders():Promise<Array<main.APIProvider>>;

export function AddClaudeAccount(arg1:string,arg2:string):Promise<string>;

export function AddLink(arg1:model.Link):Promise<model.Link>;

export function AddMachine(arg1:engine.AddSpec):Promise<string>;

export function AgentVersions(arg1:string):Promise<Array<engine.AgentVersion>>;

export function AgentsOn(arg1:string):Promise<Array<string>>;

export function AppIcon():Promise<string>;

export function CancelOp(arg1:string):Promise<void>;

export function Catalog(arg1:string):Promise<main.Catalog>;

export function CheckClaudeAccounts():Promise<string>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClaudeAccounts():Promise<Array<engine.ClaudeAccountView>>;

export function ClaudeAutoSwitch():Promise<boolean>;

export function ClaudeMoveSessions():Promise<boolean>;

export function ClaudePreciseScroll():Promise<boolean>;

export function ClaudeStatus():Promise<main.ClaudeStatus>;

export function ClaudeStrategy():Promise<string>;

export function ClipboardText():Promise<string>;

export function Clone(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CloseShell(arg1:string,arg2:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CloseTunnel(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function CopyText(arg1:string):Promise<void>;

export function CreateMachine(arg1:model.Spec):Promise<string>;

export function Credentials():Promise<Array<syncer.Credential>>;

export function DeleteMachine(arg1:string,arg2:boolean):Promise<string>;

export function DiscoverMachines():Promise<Array<engine.Candidate>>;

export function FillSpec(arg1:model.Spec):Promise<model.Spec>;

export function FindFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<engine.RemoteFile>>;

export function FocusSession(arg1:string,arg2:string):Promise<boolean>;

export function GrowDisk(arg1:string,arg2:number):Promise<string>;

export function History(arg1:string):Promise<main.HistoryView>;

export function Info():Promise<main.AppInfo>;

export function InstallTmux():Promise<string>;

export function JoinTailscale(arg1:string):Promise<string>;

export function KillSession(arg1:string,arg2:string):Promise<void>;

export function LastSyncAll():Promise<Record<string, syncer.Result>>;

export function Links():Promise<Array<model.Link>>;

export function ListDir(arg1:string,arg2:string):Promise<Array<engine.RemoteFile>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function LocalTmux():Promise<main.LocalTmuxInfo>;

export function Login(arg1:string):Promise<string>;

export function MachineHealth():Promise<main.HealthView>;

export function Machines():Promise<Array<main.MachineView>>;

export function MintClaudeToken():Promise<string>;

export function MoveClaudeAccount(arg1:string,arg2:number):Promise<void>;

export function MoveFolder(arg1:string,arg2:string,arg3:string):Promise<string>;

export function NewSession(arg1:string,arg2:engine.SessionOptions):Promise<engine.Session>;

export function NewWindow():Promise<void>;

export function NewWindowWith(arg1:string):Promise<void>;

export function NextWindow():Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenAtLogin():Promise<boolean>;

export function OpenLocalTerminal(arg1:number,arg2:number):Promise<term.Info>;

export function OpenLocalTerminalIn(arg1:string,arg2:boolean,arg3:number,arg4:number):Promise<term.Info>;

export function OpenPeeked(arg1:string):Promise<void>;

export function OpenPort(arg1:string,arg2:number,arg3:boolean):Promise<engine.Tunnel>;

export function OpenScreen(arg1:string):Promise<main.ScreenView>;

export function OpenSessionTerminal(arg1:string,arg2:string,arg3:engine.AttachOptions,arg4:number,arg5:number):Promise<term.Info>;

export function OpenTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<term.Info>;

export function OpenURL(arg1:string):Promise<void>;

export function Ops():Promise<Array<main.OpInfo>>;

export function OtherSync(arg1:string):Promise<string>;

export function PaneGit(arg1:string,arg2:string):Promise<engine.GitInfo>;

export function PaneIntent(arg1:string):Promise<boolean>;

export function PeekFile(arg1:string,arg2:engine.RemoteFile):Promise<main.PeekView>;

export function PickFile(arg1:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function PlanMove(arg1:string,arg2:string,arg3:string):Promise<engine.MovePlan>;

export function Ports(arg1:string):Promise<Array<model.Port>>;

export function ProjectAdd(arg1:string):Promise<string>;

export function ProjectBring(arg1:string,arg2:string,arg3:engine.HandoffOptions):Promise<string>;

export function ProjectForget(arg1:string,arg2:string):Promise<void>;

export function ProjectSend(arg1:string,arg2:string,arg3:engine.HandoffOptions):Promise<string>;

export function ProjectSetRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Projects(arg1:boolean):Promise<engine.ProjectList>;

export function ProviderStatuses(arg1:boolean):Promise<Array<model.ProviderStatus>>;

export function Pull(arg1:string,arg2:string,arg3:string,arg4:folders.Options):Promise<string>;

export function Push(arg1:string,arg2:string,arg3:string,arg4:folders.Options):Promise<string>;

export function RecentFiles(arg1:string,arg2:string,arg3:string):Promise<main.FilesView>;

export function RecentFolders(arg1:boolean):Promise<main.RecentFoldersView>;

export function RefreshHealth():Promise<main.HealthView>;

export function RefreshMachines():Promise<Array<main.MachineView>>;

export function RemoveAPIKey(arg1:string):Promise<string>;

export function RemoveClaudeAccount(arg1:string):Promise<void>;

export function RemoveLink(arg1:string):Promise<void>;

export function RenameClaudeAccount(arg1:string,arg2:string):Promise<void>;

export function ResizeMachine(arg1:string,arg2:string):Promise<string>;

export function RestartClaude(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RestartMachine(arg1:string):Promise<string>;

export function RestartToUpdate():Promise<void>;

export function Reveal(arg1:string):Promise<void>;

export function RevealPeeked(arg1:string):Promise<void>;

export function RunLink(arg1:string):Promise<string>;

export function SavePeeked(arg1:string):Promise<string>;

export function SaveScreenLogin(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:main.SettingsView):Promise<void>;

export function SaveWindowFrame():Promise<void>;

export function SaveWindowLayout(arg1:string):Promise<void>;

export function SearchShow(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchStart(arg1:number,arg2:string):Promise<void>;

export function SearchStop():Promise<void>;

export function SessionPorts(arg1:string):Promise<Record<string, Array<model.Port>>>;

export function Sessions():Promise<main.SessionsView>;

export function SetAPIKey(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function SetAPIKeyMachines(arg1:string,arg2:Array<string>):Promise<string>;

export function SetAPIKeySync(arg1:string,arg2:boolean):Promise<string>;

export function SetAppIcon(arg1:string):Promise<void>;

export function SetAutoUpdate(arg1:boolean):Promise<void>;

export function SetClaudeAccountEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetClaudeAutoSwitch(arg1:boolean):Promise<void>;

export function SetClaudeMoveSessions(arg1:boolean):Promise<void>;

export function SetClaudePreciseScroll(arg1:boolean):Promise<void>;

export function SetClaudeStrategy(arg1:string):Promise<void>;

export function SetClaudeToken(arg1:string):Promise<void>;

export function SetIdle(arg1:string,arg2:number):Promise<string>;

export function SetLinkWatch(arg1:string,arg2:boolean):Promise<void>;

export function SetOpenAtLogin(arg1:boolean):Promise<void>;

export function SetSyncItems(arg1:string,arg2:Array<string>):Promise<void>;

export function SetTailscaleAuthKey(arg1:string):Promise<void>;

export function Settings():Promise<main.SettingsView>;

export function StartMachine(arg1:string):Promise<string>;

export function StopMachine(arg1:string):Promise<string>;

export function SyncMachines(arg1:Array<string>,arg2:Array<string>):Promise<string>;

export function TailscaleStatus():Promise<engine.TailscaleInfo>;

export function TakeOverSync(arg1:string):Promise<string>;

export function TakeSession(arg1:string,arg2:string):Promise<boolean>;

export function Terminal(arg1:string):Promise<term.Info>;

export function TerminalInfo(arg1:string):Promise<term.Probe>;

export function TestAPIKey(arg1:string):Promise<main.KeyTest>;

export function Tunnels():Promise<Array<engine.Tunnel>>;

export function UpdateInfo():Promise<main.UpdateInfo>;

export function UseClaudeAccount(arg1:string):Promise<string>;

export function WatchedLinks():Promise<Array<string>>;

export function WindowInfo():Promise<main.WindowInfo>;

export function WindowLayout():Promise<string>;

export function WindowSessions(arg1:Array<string>):Promise<void>;

export function WindowsCleared(arg1:Array<string>):Promise<void>;
