// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Click(arg1:number,arg2:number,arg3:Array<string>):Promise<void>;

export function Exec(arg1:string):Promise<void>;

export function Frame():Promise<main.frame>;

export function Get(arg1:string):Promise<string>;

export function Key(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Array<string>):Promise<void>;

export function Put(arg1:string,arg2:string):Promise<void>;

export function SavedFrames():Promise<Record<string, main.frame>>;

export function Scale(arg1:number):Promise<void>;

export function Screens():Promise<string>;

export function SetFrame(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function Snapshot(arg1:string):Promise<void>;

export function Stage():Promise<number>;
