// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Click(arg1, arg2, arg3) {
  return window['go']['main']['Debug']['Click'](arg1, arg2, arg3);
}

export function Exec(arg1) {
  return window['go']['main']['Debug']['Exec'](arg1);
}

export function Frame() {
  return window['go']['main']['Debug']['Frame']();
}

export function Get(arg1) {
  return window['go']['main']['Debug']['Get'](arg1);
}

export function Key(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['Debug']['Key'](arg1, arg2, arg3, arg4, arg5);
}

export function Put(arg1, arg2) {
  return window['go']['main']['Debug']['Put'](arg1, arg2);
}

export function SavedFrames() {
  return window['go']['main']['Debug']['SavedFrames']();
}

export function Scale(arg1) {
  return window['go']['main']['Debug']['Scale'](arg1);
}

export function Screens() {
  return window['go']['main']['Debug']['Screens']();
}

export function SetFrame(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Debug']['SetFrame'](arg1, arg2, arg3, arg4);
}

export function Snapshot(arg1) {
  return window['go']['main']['Debug']['Snapshot'](arg1);
}

export function Stage() {
  return window['go']['main']['Debug']['Stage']();
}
